### ISSUE TITLE
Dynamic namespacing

### ISSUE THREAD

**Issue by KidkArolis** [QubitProducts/driftwood#46]
I will have a look at the code, but was wondering if it's safe to create temporary loggers, or will that run out of memory? e.g.:

```
const jobLog = log(`job:${job.id}`)
jobLog.info('bla')
```

**Comment by oliverwoodings** [comment]
Good question, I have a funny feeling the parent might hold reference to it's children, but perhaps we could have a dispose function.

**Comment by KidkArolis** [comment]
Looks like it already has `destroy` method: https://github.com/QubitProducts/driftwood/blob/master/src/create.js#L70
